export interface CurrencyListEntry {
  code: string;
  name: string;
  symbol: string;
  iso2: string;
  countryCode: string | null;
}

export interface CountryCodeEntry {
  code: string;
  iso2: string;
  name: string;
  digits: { min: number; max: number };
}

export interface VehicleOption {
  id: string;
  label: string;
  icon: string;
  maxWeightKg: number;
}

export interface VehicleCategory {
  category: string;
  vehicles: VehicleOption[];
}

export const CURRENCY_LIST: CurrencyListEntry[] = [
    { code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ", iso2: "AE", countryCode: "+971" },
    { code: "AFN", name: "Afghan Afghani", symbol: "؋", iso2: "AF", countryCode: "+93" },
    { code: "ALL", name: "Albanian Lek", symbol: "L", iso2: "AL", countryCode: "+355" },
    { code: "AMD", name: "Armenian Dram", symbol: "֏", iso2: "AM", countryCode: "+374" },
    { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", iso2: "CW", countryCode: "+599" },
    { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", iso2: "AO", countryCode: "+244" },
    { code: "ARS", name: "Argentine Peso", symbol: "$", iso2: "AR", countryCode: "+54" },
    { code: "AUD", name: "Australian Dollar", symbol: "A$", iso2: "AU", countryCode: "+61" },
    { code: "AWG", name: "Aruban Florin", symbol: "ƒ", iso2: "AW", countryCode: "+297" },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", iso2: "AZ", countryCode: "+994" },
    { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", iso2: "BA", countryCode: "+387" },
    { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", iso2: "BB", countryCode: "+1" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", iso2: "BD", countryCode: "+880" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв", iso2: "BG", countryCode: "+359" },
    { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", iso2: "BH", countryCode: "+973" },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu", iso2: "BI", countryCode: "+257" },
    { code: "BMD", name: "Bermudan Dollar", symbol: "Bd$", iso2: "BM", countryCode: "+1" },
    { code: "BND", name: "Brunei Dollar", symbol: "B$", iso2: "BN", countryCode: "+673" },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", iso2: "BO", countryCode: "+591" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$", iso2: "BR", countryCode: "+55" },
    { code: "BSD", name: "Bahamian Dollar", symbol: "B$", iso2: "BS", countryCode: "+1" },
    { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", iso2: "BT", countryCode: "+975" },
    { code: "BWP", name: "Botswanan Pula", symbol: "P", iso2: "BW", countryCode: "+267" },
    { code: "BYN", name: "Belarusian Ruble", symbol: "Br", iso2: "BY", countryCode: "+375" },
    { code: "BZD", name: "Belize Dollar", symbol: "BZ$", iso2: "BZ", countryCode: "+501" },
    { code: "CAD", name: "Canadian Dollar", symbol: "C$", iso2: "CA", countryCode: "+1" },
    { code: "CDF", name: "Congolese Franc", symbol: "FC", iso2: "CD", countryCode: "+243" },
    { code: "CHF", name: "Swiss Franc", symbol: "CHF", iso2: "CH", countryCode: "+41" },
    { code: "CLP", name: "Chilean Peso", symbol: "$", iso2: "CL", countryCode: "+56" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥", iso2: "CN", countryCode: "+86" },
    { code: "COP", name: "Colombian Peso", symbol: "$", iso2: "CO", countryCode: "+57" },
    { code: "CRC", name: "Costa Rican Colón", symbol: "₡", iso2: "CR", countryCode: "+506" },
    { code: "CUP", name: "Cuban Peso", symbol: "₱", iso2: "CU", countryCode: "+53" },
    { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc", iso2: "CV", countryCode: "+238" },
    { code: "CZK", name: "Czech Republic Koruna", symbol: "Kč", iso2: "CZ", countryCode: "+420" },
    { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", iso2: "DJ", countryCode: "+253" },
    { code: "DKK", name: "Danish Krone", symbol: "kr", iso2: "DK", countryCode: "+45" },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$", iso2: "DO", countryCode: "+1" },
    { code: "DZD", name: "Algerian Dinar", symbol: "دج", iso2: "DZ", countryCode: "+213" },
    { code: "EGP", name: "Egyptian Pound", symbol: "£", iso2: "EG", countryCode: "+20" },
    { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", iso2: "ER", countryCode: "+291" },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br", iso2: "ET", countryCode: "+251" },
    { code: "EUR", name: "Euro", symbol: "€", iso2: "EU", countryCode: "+33" },
    { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", iso2: "FJ", countryCode: "+679" },
    { code: "FKP", name: "Falkland Islands Pound", symbol: "£", iso2: "FK", countryCode: "+500" },
    { code: "GBP", name: "British Pound Sterling", symbol: "£", iso2: "GB", countryCode: "+44" },
    { code: "GEL", name: "Georgian Lari", symbol: "₾", iso2: "GE", countryCode: "+995" },
    { code: "GGP", name: "Guernsey Pound", symbol: "£", iso2: "GG", countryCode: "+44" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵", iso2: "GH", countryCode: "+233" },
    { code: "GIP", name: "Gibraltar Pound", symbol: "£", iso2: "GI", countryCode: "+350" },
    { code: "GMD", name: "Gambian Dalasi", symbol: "D", iso2: "GM", countryCode: "+220" },
    { code: "GNF", name: "Guinean Franc", symbol: "FG", iso2: "GN", countryCode: "+224" },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", iso2: "GT", countryCode: "+502" },
    { code: "GYD", name: "Guyanaese Dollar", symbol: "$", iso2: "GY", countryCode: "+592" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", iso2: "HK", countryCode: "+852" },
    { code: "HNL", name: "Honduran Lempira", symbol: "L", iso2: "HN", countryCode: "+504" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn", iso2: "HR", countryCode: "+385" },
    { code: "HTG", name: "Haitian Gourde", symbol: "G", iso2: "HT", countryCode: "+509" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft", iso2: "HU", countryCode: "+36" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", iso2: "ID", countryCode: "+62" },
    { code: "ILS", name: "Israeli New Sheqel", symbol: "₪", iso2: "IL", countryCode: "+972" },
    { code: "IMP", name: "Isle of Man Pound", symbol: "£", iso2: "IM", countryCode: "+44" },
    { code: "INR", name: "Indian Rupee", symbol: "₹", iso2: "IN", countryCode: "+91" },
    { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", iso2: "IQ", countryCode: "+964" },
    { code: "IRR", name: "Iranian Rial", symbol: "﷼", iso2: "IR", countryCode: "+98" },
    { code: "ISK", name: "Icelandic Króna", symbol: "kr", iso2: "IS", countryCode: "+354" },
    { code: "JEP", name: "Jersey Pound", symbol: "£", iso2: "JE", countryCode: "+44" },
    { code: "JMD", name: "Jamaican Dollar", symbol: "J$", iso2: "JM", countryCode: "+1" },
    { code: "JOD", name: "Jordanian Dinar", symbol: "JD", iso2: "JO", countryCode: "+962" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥", iso2: "JP", countryCode: "+81" },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh", iso2: "KE", countryCode: "+254" },
    { code: "KGS", name: "Kyrgystani Som", symbol: "лв", iso2: "KG", countryCode: "+996" },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛", iso2: "KH", countryCode: "+855" },
    { code: "KMF", name: "Comorian Franc", symbol: "CF", iso2: "KM", countryCode: "+269" },
    { code: "KPW", name: "North Korean Won", symbol: "₩", iso2: "KP", countryCode: "+850" },
    { code: "KRW", name: "South Korean Won", symbol: "₩", iso2: "KR", countryCode: "+82" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "KD", iso2: "KW", countryCode: "+965" },
    { code: "KYD", name: "Cayman Islands Dollar", symbol: "KY$", iso2: "KY", countryCode: "+1" },
    { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", iso2: "KZ", countryCode: "+7" },
    { code: "LAK", name: "Laotian Kip", symbol: "₭", iso2: "LA", countryCode: "+856" },
    { code: "LBP", name: "Lebanese Pound", symbol: "£", iso2: "LB", countryCode: "+961" },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", iso2: "LK", countryCode: "+94" },
    { code: "LRD", name: "Liberian Dollar", symbol: "L$", iso2: "LR", countryCode: "+231" },
    { code: "LSL", name: "Lesotho Loti", symbol: "M", iso2: "LS", countryCode: "+266" },
    { code: "LYD", name: "Libyan Dinar", symbol: "LD", iso2: "LY", countryCode: "+218" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "MAD", iso2: "MA", countryCode: "+212" },
    { code: "MDL", name: "Moldovan Leu", symbol: "L", iso2: "MD", countryCode: "+373" },
    { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", iso2: "MG", countryCode: "+261" },
    { code: "MKD", name: "Macedonian Denar", symbol: "ден", iso2: "MK", countryCode: "+389" },
    { code: "MMK", name: "Myanma Kyat", symbol: "Ks", iso2: "MM", countryCode: "+95" },
    { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", iso2: "MN", countryCode: "+976" },
    { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", iso2: "MO", countryCode: "+853" },
    { code: "MRU", name: "Mauritanian Ouguiya", symbol: "MRU", iso2: "MR", countryCode: "+222" },
    { code: "MUR", name: "Mauritian Rupee", symbol: "₨", iso2: "MU", countryCode: "+230" },
    { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", iso2: "MV", countryCode: "+960" },
    { code: "MWK", name: "Malawian Kwacha", symbol: "MK", iso2: "MW", countryCode: "+265" },
    { code: "MXN", name: "Mexican Peso", symbol: "$", iso2: "MX", countryCode: "+52" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", iso2: "MY", countryCode: "+60" },
    { code: "MZN", name: "Mozambican Metical", symbol: "MT", iso2: "MZ", countryCode: "+258" },
    { code: "NAD", name: "Namibian Dollar", symbol: "N$", iso2: "NA", countryCode: "+264" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦", iso2: "NG", countryCode: "+234" },
    { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", iso2: "NI", countryCode: "+505" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr", iso2: "NO", countryCode: "+47" },
    { code: "NPR", name: "Nepalese Rupee", symbol: "₨", iso2: "NP", countryCode: "+977" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", iso2: "NZ", countryCode: "+64" },
    { code: "OMR", name: "Omani Rial", symbol: "﷼", iso2: "OM", countryCode: "+968" },
    { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", iso2: "PA", countryCode: "+507" },
    { code: "PEN", name: "Peruvian Nuevo Sol", symbol: "S/.", iso2: "PE", countryCode: "+51" },
    { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", iso2: "PG", countryCode: "+675" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱", iso2: "PH", countryCode: "+63" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨", iso2: "PK", countryCode: "+92" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł", iso2: "PL", countryCode: "+48" },
    { code: "PYG", name: "Paraguayan Guarani", symbol: "Gs", iso2: "PY", countryCode: "+595" },
    { code: "QAR", name: "Qatari Rial", symbol: "﷼", iso2: "QA", countryCode: "+974" },
    { code: "RON", name: "Romanian Leu", symbol: "lei", iso2: "RO", countryCode: "+40" },
    { code: "RSD", name: "Serbian Dinar", symbol: "Дин.|RSD", iso2: "RS", countryCode: "+381" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽", iso2: "RU", countryCode: "+7" },
    { code: "RWF", name: "Rwandan Franc", symbol: "FRw", iso2: "RW", countryCode: "+250" },
    { code: "SAR", name: "Saudi Riyal", symbol: "﷼", iso2: "SA", countryCode: "+966" },
    { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", iso2: "SB", countryCode: "+677" },
    { code: "SCR", name: "Seychellois Rupee", symbol: "₨", iso2: "SC", countryCode: "+248" },
    { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", iso2: "SD", countryCode: "+249" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr", iso2: "SE", countryCode: "+46" },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$", iso2: "SG", countryCode: "+65" },
    { code: "SHP", name: "Saint Helena Pound", symbol: "£", iso2: "SH", countryCode: "+290" },
    { code: "SLE", name: "Sierra Leonean Leone (new)", symbol: "Le", iso2: "SL", countryCode: "+232" },
    { code: "SLL", name: "Sierra Leonean Leone (old)", symbol: "Le", iso2: "SL", countryCode: "+232" },
    { code: "SOS", name: "Somali Shilling", symbol: "S", iso2: "SO", countryCode: "+252" },
    { code: "SRD", name: "Surinamese Dollar", symbol: "$", iso2: "SR", countryCode: "+597" },
    { code: "SSP", name: "South Sudanese Pound", symbol: "£", iso2: "SS", countryCode: "+211" },
    { code: "STN", name: "São Tomé and Príncipe Dobra (new)", symbol: "Db", iso2: "ST", countryCode: "+239" },
    { code: "STD", name: "São Tomé and Príncipe Dobra (old)", symbol: "Db", iso2: "ST", countryCode: "+239" },
    { code: "SYP", name: "Syrian Pound", symbol: "£", iso2: "SY", countryCode: "+963" },
    { code: "SZL", name: "Swazi Lilangeni", symbol: "L", iso2: "SZ", countryCode: "+268" },
    { code: "THB", name: "Thai Baht", symbol: "฿", iso2: "TH", countryCode: "+66" },
    { code: "TJS", name: "Tajikistani Somoni", symbol: "s", iso2: "TJ", countryCode: "+992" },
    { code: "TMT", name: "Turkmenistani Manat", symbol: "m", iso2: "TM", countryCode: "+993" },
    { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", iso2: "TN", countryCode: "+216" },
    { code: "TOP", name: "Tongan Pa'anga", symbol: "T$", iso2: "TO", countryCode: "+676" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺", iso2: "TR", countryCode: "+90" },
    { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", iso2: "TT", countryCode: "+1" },
    { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", iso2: "TW", countryCode: "+886" },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", iso2: "TZ", countryCode: "+255" },
    { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", iso2: "UA", countryCode: "+380" },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh", iso2: "UG", countryCode: "+256" },
    { code: "USD", name: "United States Dollar", symbol: "$", iso2: "US", countryCode: "+1" },
    { code: "UYU", name: "Uruguayan Peso", symbol: "$U", iso2: "UY", countryCode: "+598" },
    { code: "UZS", name: "Uzbekistan Som", symbol: "сўм", iso2: "UZ", countryCode: "+998" },
    { code: "VES", name: "Venezuelan Bolívar Soberano", symbol: "Bs.S", iso2: "VE", countryCode: "+58" },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫", iso2: "VN", countryCode: "+84" },
    { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", iso2: "VU", countryCode: "+678" },
    { code: "WST", name: "Samoan Tala", symbol: "T", iso2: "WS", countryCode: "+685" },
    { code: "XAF", name: "CFA Franc BEAC", symbol: "FCFA", iso2: "CM", countryCode: "+237" },
    { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", iso2: "DM", countryCode: "+1" },
    { code: "XDR", name: "Special Drawing Rights", symbol: "SDR", iso2: "XX", countryCode: null },
    { code: "XOF", name: "CFA Franc BCEAO", symbol: "CFA", iso2: "CI", countryCode: "+225" },
    { code: "XPF", name: "CFP Franc", symbol: "Fr", iso2: "PF", countryCode: "+689" },
    { code: "YER", name: "Yemeni Rial", symbol: "﷼", iso2: "YE", countryCode: "+967" },
    { code: "ZAR", name: "South African Rand", symbol: "R", iso2: "ZA", countryCode: "+27" },
    { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", iso2: "ZM", countryCode: "+260" },
    { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", iso2: "ZW", countryCode: "+263" },
];

export const COUNTRY_CODES: CountryCodeEntry[] = [
    { code: "+93", iso2: "AF", name: "Afghanistan", digits: { min: 9, max: 9 } },
    { code: "+355", iso2: "AL", name: "Albania", digits: { min: 8, max: 9 } },
    { code: "+213", iso2: "DZ", name: "Algeria", digits: { min: 8, max: 9 } },
    { code: "+1684", iso2: "AS", name: "American Samoa", digits: { min: 7, max: 7 } },
    { code: "+376", iso2: "AD", name: "Andorra", digits: { min: 6, max: 6 } },
    { code: "+244", iso2: "AO", name: "Angola", digits: { min: 9, max: 9 } },
    { code: "+1264", iso2: "AI", name: "Anguilla", digits: { min: 7, max: 7 } },
    { code: "+672", iso2: "AQ", name: "Antarctica", digits: { min: 0, max: 0 } },
    { code: "+1268", iso2: "AG", name: "Antigua and Barbuda", digits: { min: 7, max: 7 } },
    { code: "+54", iso2: "AR", name: "Argentina", digits: { min: 10, max: 11 } },
    { code: "+374", iso2: "AM", name: "Armenia", digits: { min: 8, max: 8 } },
    { code: "+297", iso2: "AW", name: "Aruba", digits: { min: 7, max: 7 } },
    { code: "+61", iso2: "AU", name: "Australia", digits: { min: 9, max: 9 } },
    { code: "+43", iso2: "AT", name: "Austria", digits: { min: 10, max: 13 } },
    { code: "+994", iso2: "AZ", name: "Azerbaijan", digits: { min: 9, max: 9 } },
    { code: "+1242", iso2: "BS", name: "Bahamas", digits: { min: 7, max: 7 } },
    { code: "+973", iso2: "BH", name: "Bahrain", digits: { min: 8, max: 8 } },
    { code: "+880", iso2: "BD", name: "Bangladesh", digits: { min: 11, max: 11 } },
    { code: "+1246", iso2: "BB", name: "Barbados", digits: { min: 7, max: 7 } },
    { code: "+375", iso2: "BY", name: "Belarus", digits: { min: 9, max: 9 } },
    { code: "+32", iso2: "BE", name: "Belgium", digits: { min: 8, max: 9 } },
    { code: "+501", iso2: "BZ", name: "Belize", digits: { min: 7, max: 7 } },
    { code: "+229", iso2: "BJ", name: "Benin", digits: { min: 8, max: 8 } },
    { code: "+1441", iso2: "BM", name: "Bermuda", digits: { min: 7, max: 7 } },
    { code: "+975", iso2: "BT", name: "Bhutan", digits: { min: 8, max: 8 } },
    { code: "+591", iso2: "BO", name: "Bolivia", digits: { min: 8, max: 8 } },
    { code: "+387", iso2: "BA", name: "Bosnia and Herzegovina", digits: { min: 8, max: 9 } },
    { code: "+267", iso2: "BW", name: "Botswana", digits: { min: 8, max: 8 } },
    { code: "+55", iso2: "BR", name: "Brazil", digits: { min: 10, max: 11 } },
    { code: "+1284", iso2: "VG", name: "British Virgin Islands", digits: { min: 7, max: 7 } },
    { code: "+673", iso2: "BN", name: "Brunei", digits: { min: 7, max: 7 } },
    { code: "+359", iso2: "BG", name: "Bulgaria", digits: { min: 9, max: 9 } },
    { code: "+226", iso2: "BF", name: "Burkina Faso", digits: { min: 8, max: 8 } },
    { code: "+95", iso2: "MM", name: "Burma", digits: { min: 11, max: 11 } },
    { code: "+257", iso2: "BI", name: "Burundi", digits: { min: 8, max: 8 } },
    { code: "+855", iso2: "KH", name: "Cambodia", digits: { min: 9, max: 10 } },
    { code: "+237", iso2: "CM", name: "Cameroon", digits: { min: 9, max: 9 } },
    { code: "+1", iso2: "CA", name: "Canada", digits: { min: 10, max: 10 } },
    { code: "+238", iso2: "CV", name: "Cape Verde", digits: { min: 7, max: 7 } },
    { code: "+1345", iso2: "KY", name: "Cayman Islands", digits: { min: 7, max: 7 } },
    { code: "+236", iso2: "CF", name: "Central African Republic", digits: { min: 8, max: 8 } },
    { code: "+235", iso2: "TD", name: "Chad", digits: { min: 8, max: 8 } },
    { code: "+56", iso2: "CL", name: "Chile", digits: { min: 9, max: 9 } },
    { code: "+86", iso2: "CN", name: "China", digits: { min: 11, max: 11 } },
    { code: "+61", iso2: "CX", name: "Christmas Island", digits: { min: 7, max: 7 } },
    { code: "+61", iso2: "CC", name: "Cocos (Keeling) Islands", digits: { min: 7, max: 7 } },
    { code: "+57", iso2: "CO", name: "Colombia", digits: { min: 10, max: 10 } },
    { code: "+269", iso2: "KM", name: "Comoros", digits: { min: 7, max: 7 } },
    { code: "+242", iso2: "CG", name: "Republic of the Congo", digits: { min: 7, max: 9 } },
    { code: "+243", iso2: "CD", name: "Democratic Republic of the Congo", digits: { min: 9, max: 9 } },
    { code: "+682", iso2: "CK", name: "Cook Islands", digits: { min: 5, max: 5 } },
    { code: "+506", iso2: "CR", name: "Costa Rica", digits: { min: 8, max: 8 } },
    { code: "+225", iso2: "CI", name: "Côte d'Ivoire", digits: { min: 8, max: 8 } },
    { code: "+385", iso2: "HR", name: "Croatia", digits: { min: 8, max: 9 } },
    { code: "+53", iso2: "CU", name: "Cuba", digits: { min: 8, max: 8 } },
    { code: "+357", iso2: "CY", name: "Cyprus", digits: { min: 8, max: 8 } },
    { code: "+420", iso2: "CZ", name: "Czech Republic", digits: { min: 9, max: 9 } },
    { code: "+45", iso2: "DK", name: "Denmark", digits: { min: 8, max: 8 } },
    { code: "+253", iso2: "DJ", name: "Djibouti", digits: { min: 9, max: 9 } },
    { code: "+1767", iso2: "DM", name: "Dominica", digits: { min: 7, max: 7 } },
    { code: "+1849", iso2: "DO", name: "Dominican Republic", digits: { min: 10, max: 10 } },
    { code: "+670", iso2: "TL", name: "East Timor", digits: { min: 8, max: 8 } },
    { code: "+56", iso2: "CL", name: "Easter Island", digits: { min: 7, max: 7 } },
    { code: "+593", iso2: "EC", name: "Ecuador", digits: { min: 10, max: 10 } },
    { code: "+20", iso2: "EG", name: "Egypt", digits: { min: 8, max: 11 } },
    { code: "+503", iso2: "SV", name: "El Salvador", digits: { min: 8, max: 8 } },
    { code: "+240", iso2: "GQ", name: "Equatorial Guinea", digits: { min: 9, max: 9 } },
    { code: "+291", iso2: "ER", name: "Eritrea", digits: { min: 7, max: 7 } },
    { code: "+372", iso2: "EE", name: "Estonia", digits: { min: 7, max: 8 } },
    { code: "+251", iso2: "ET", name: "Ethiopia", digits: { min: 9, max: 9 } },
    { code: "+500", iso2: "FK", name: "Falkland Islands (Islas Malvinas)", digits: { min: 5, max: 5 } },
    { code: "+298", iso2: "FO", name: "Faroe Islands", digits: { min: 6, max: 6 } },
    { code: "+679", iso2: "FJ", name: "Fiji", digits: { min: 7, max: 7 } },
    { code: "+358", iso2: "FI", name: "Finland", digits: { min: 8, max: 10 } },
    { code: "+33", iso2: "FR", name: "France", digits: { min: 9, max: 9 } },
    { code: "+689", iso2: "PF", name: "French Polynesia", digits: { min: 8, max: 8 } },
    { code: "+241", iso2: "GA", name: "Gabon", digits: { min: 7, max: 7 } },
    { code: "+220", iso2: "GM", name: "Gambia", digits: { min: 7, max: 7 } },
    { code: "+995", iso2: "GE", name: "Georgia", digits: { min: 9, max: 9 } },
    { code: "+49", iso2: "DE", name: "Germany", digits: { min: 10, max: 11 } },
    { code: "+233", iso2: "GH", name: "Ghana", digits: { min: 9, max: 10 } },
    { code: "+350", iso2: "GI", name: "Gibraltar", digits: { min: 8, max: 8 } },
    { code: "+30", iso2: "GR", name: "Greece", digits: { min: 10, max: 10 } },
    { code: "+299", iso2: "GL", name: "Greenland", digits: { min: 6, max: 6 } },
    { code: "+1473", iso2: "GD", name: "Grenada", digits: { min: 7, max: 7 } },
    { code: "+1671", iso2: "GU", name: "Guam", digits: { min: 7, max: 7 } },
    { code: "+502", iso2: "GT", name: "Guatemala", digits: { min: 8, max: 8 } },
    { code: "+224", iso2: "GN", name: "Guinea", digits: { min: 8, max: 9 } },
    { code: "+245", iso2: "GW", name: "Guinea-Bissau", digits: { min: 7, max: 7 } },
    { code: "+592", iso2: "GY", name: "Guyana", digits: { min: 7, max: 7 } },
    { code: "+509", iso2: "HT", name: "Haiti", digits: { min: 8, max: 8 } },
    { code: "+504", iso2: "HN", name: "Honduras", digits: { min: 8, max: 8 } },
    { code: "+852", iso2: "HK", name: "Hong Kong", digits: { min: 8, max: 8 } },
    { code: "+36", iso2: "HU", name: "Hungary", digits: { min: 9, max: 9 } },
    { code: "+354", iso2: "IS", name: "Iceland", digits: { min: 7, max: 7 } },
    { code: "+91", iso2: "IN", name: "India", digits: { min: 10, max: 10 } },
    { code: "+62", iso2: "ID", name: "Indonesia", digits: { min: 10, max: 13 } },
    { code: "+98", iso2: "IR", name: "Iran", digits: { min: 10, max: 10 } },
    { code: "+964", iso2: "IQ", name: "Iraq", digits: { min: 10, max: 10 } },
    { code: "+353", iso2: "IE", name: "Ireland", digits: { min: 7, max: 7 } },
    { code: "+972", iso2: "IL", name: "Israel", digits: { min: 8, max: 10 } },
    { code: "+39", iso2: "IT", name: "Italy", digits: { min: 9, max: 10 } },
    { code: "+1876", iso2: "JM", name: "Jamaica", digits: { min: 7, max: 7 } },
    { code: "+81", iso2: "JP", name: "Japan", digits: { min: 10, max: 10 } },
    { code: "+962", iso2: "JO", name: "Jordan", digits: { min: 8, max: 8 } },
    { code: "+7", iso2: "KZ", name: "Kazakhstan", digits: { min: 10, max: 10 } },
    { code: "+254", iso2: "KE", name: "Kenya", digits: { min: 9, max: 9 } },
    { code: "+686", iso2: "KI", name: "Kiribati", digits: { min: 8, max: 8 } },
    { code: "+850", iso2: "KP", name: "Korea, North", digits: { min: 9, max: 10 } },
    { code: "+82", iso2: "KR", name: "Korea, South", digits: { min: 9, max: 11 } },
    { code: "+965", iso2: "KW", name: "Kuwait", digits: { min: 8, max: 8 } },
    { code: "+996", iso2: "KG", name: "Kyrgyzstan", digits: { min: 9, max: 9 } },
    { code: "+856", iso2: "LA", name: "Laos", digits: { min: 8, max: 9 } },
    { code: "+371", iso2: "LV", name: "Latvia", digits: { min: 8, max: 8 } },
    { code: "+961", iso2: "LB", name: "Lebanon", digits: { min: 7, max: 8 } },
    { code: "+266", iso2: "LS", name: "Lesotho", digits: { min: 8, max: 8 } },
    { code: "+231", iso2: "LR", name: "Liberia", digits: { min: 7, max: 8 } },
    { code: "+218", iso2: "LY", name: "Libya", digits: { min: 9, max: 10 } },
    { code: "+423", iso2: "LI", name: "Liechtenstein", digits: { min: 7, max: 7 } },
    { code: "+370", iso2: "LT", name: "Lithuania", digits: { min: 8, max: 8 } },
    { code: "+352", iso2: "LU", name: "Luxembourg", digits: { min: 9, max: 9 } },
    { code: "+853", iso2: "MO", name: "Macau", digits: { min: 8, max: 8 } },
    { code: "+389", iso2: "MK", name: "Macedonia", digits: { min: 8, max: 9 } },
    { code: "+261", iso2: "MG", name: "Madagascar", digits: { min: 9, max: 10 } },
    { code: "+265", iso2: "MW", name: "Malawi", digits: { min: 9, max: 9 } },
    { code: "+60", iso2: "MY", name: "Malaysia", digits: { min: 9, max: 10 } },
    { code: "+960", iso2: "MV", name: "Maldives", digits: { min: 7, max: 7 } },
    { code: "+223", iso2: "ML", name: "Mali", digits: { min: 8, max: 8 } },
    { code: "+356", iso2: "MT", name: "Malta", digits: { min: 8, max: 8 } },
    { code: "+692", iso2: "MH", name: "Marshall Islands", digits: { min: 7, max: 7 } },
    { code: "+222", iso2: "MR", name: "Mauritania", digits: { min: 8, max: 8 } },
    { code: "+230", iso2: "MU", name: "Mauritius", digits: { min: 8, max: 8 } },
    { code: "+269", iso2: "YT", name: "Mayotte", digits: { min: 9, max: 9 } },
    { code: "+52", iso2: "MX", name: "Mexico", digits: { min: 10, max: 10 } },
    { code: "+691", iso2: "FM", name: "Micronesia", digits: { min: 7, max: 7 } },
    { code: "+373", iso2: "MD", name: "Moldova", digits: { min: 8, max: 8 } },
    { code: "+377", iso2: "MC", name: "Monaco", digits: { min: 8, max: 9 } },
    { code: "+976", iso2: "MN", name: "Mongolia", digits: { min: 8, max: 8 } },
    { code: "+382", iso2: "ME", name: "Montenegro", digits: { min: 8, max: 8 } },
    { code: "+1664", iso2: "MS", name: "Montserrat", digits: { min: 7, max: 7 } },
    { code: "+212", iso2: "MA", name: "Morocco", digits: { min: 9, max: 9 } },
    { code: "+258", iso2: "MZ", name: "Mozambique", digits: { min: 9, max: 9 } },
    { code: "+95", iso2: "MM", name: "Myanmar", digits: { min: 11, max: 11 } },
    { code: "+264", iso2: "NA", name: "Namibia", digits: { min: 7, max: 9 } },
    { code: "+674", iso2: "NR", name: "Nauru", digits: { min: 7, max: 7 } },
    { code: "+977", iso2: "NP", name: "Nepal", digits: { min: 10, max: 10 } },
    { code: "+31", iso2: "NL", name: "Netherlands", digits: { min: 9, max: 10 } },
    { code: "+599", iso2: "AN", name: "Netherlands Antilles", digits: { min: 7, max: 7 } },
    { code: "+687", iso2: "NC", name: "New Caledonia", digits: { min: 6, max: 6 } },
    { code: "+64", iso2: "NZ", name: "New Zealand", digits: { min: 7, max: 11 } },
    { code: "+505", iso2: "NI", name: "Nicaragua", digits: { min: 8, max: 8 } },
    { code: "+227", iso2: "NE", name: "Niger", digits: { min: 8, max: 8 } },
    { code: "+234", iso2: "NG", name: "Nigeria", digits: { min: 10, max: 11 } },
    { code: "+683", iso2: "NU", name: "Niue", digits: { min: 4, max: 8 } },
    { code: "+850", iso2: "KP", name: "North Korea", digits: { min: 9, max: 10 } },
    { code: "+47", iso2: "NO", name: "Norway", digits: { min: 8, max: 8 } },
    { code: "+968", iso2: "OM", name: "Oman", digits: { min: 8, max: 8 } },
    { code: "+92", iso2: "PK", name: "Pakistan", digits: { min: 10, max: 10 } },
    { code: "+680", iso2: "PW", name: "Palau", digits: { min: 7, max: 7 } },
    { code: "+507", iso2: "PA", name: "Panama", digits: { min: 7, max: 8 } },
    { code: "+675", iso2: "PG", name: "Papua New Guinea", digits: { min: 7, max: 8 } },
    { code: "+595", iso2: "PY", name: "Paraguay", digits: { min: 9, max: 9 } },
    { code: "+51", iso2: "PE", name: "Peru", digits: { min: 9, max: 9 } },
    { code: "+63", iso2: "PH", name: "Philippines", digits: { min: 10, max: 10 } },
    { code: "+64", iso2: "PN", name: "Pitcairn Islands", digits: { min: 7, max: 7 } },
    { code: "+48", iso2: "PL", name: "Poland", digits: { min: 9, max: 9 } },
    { code: "+351", iso2: "PT", name: "Portugal", digits: { min: 9, max: 9 } },
    { code: "+1", iso2: "PR", name: "Puerto Rico", digits: { min: 10, max: 10 } },
    { code: "+974", iso2: "QA", name: "Qatar", digits: { min: 8, max: 8 } },
    { code: "+40", iso2: "RO", name: "Romania", digits: { min: 9, max: 9 } },
    { code: "+7", iso2: "RU", name: "Russia", digits: { min: 10, max: 10 } },
    { code: "+250", iso2: "RW", name: "Rwanda", digits: { min: 9, max: 9 } },
    { code: "+590", iso2: "BL", name: "Saint Barthélemy", digits: { min: 9, max: 9 } },
    { code: "+685", iso2: "WS", name: "Samoa", digits: { min: 7, max: 7 } },
    { code: "+378", iso2: "SM", name: "San Marino", digits: { min: 10, max: 10 } },
    { code: "+239", iso2: "ST", name: "São Tomé and Príncipe", digits: { min: 7, max: 7 } },
    { code: "+966", iso2: "SA", name: "Saudi Arabia", digits: { min: 9, max: 9 } },
    { code: "+221", iso2: "SN", name: "Senegal", digits: { min: 9, max: 9 } },
    { code: "+381", iso2: "RS", name: "Serbia", digits: { min: 8, max: 10 } },
    { code: "+248", iso2: "SC", name: "Seychelles", digits: { min: 7, max: 7 } },
    { code: "+232", iso2: "SL", name: "Sierra Leone", digits: { min: 8, max: 8 } },
    { code: "+65", iso2: "SG", name: "Singapore", digits: { min: 8, max: 8 } },
    { code: "+421", iso2: "SK", name: "Slovakia", digits: { min: 9, max: 9 } },
    { code: "+386", iso2: "SI", name: "Slovenia", digits: { min: 8, max: 8 } },
    { code: "+677", iso2: "SB", name: "Solomon Islands", digits: { min: 7, max: 7 } },
    { code: "+252", iso2: "SO", name: "Somalia", digits: { min: 8, max: 9 } },
    { code: "+27", iso2: "ZA", name: "South Africa", digits: { min: 9, max: 9 } },
    { code: "+211", iso2: "SS", name: "South Sudan", digits: { min: 9, max: 9 } },
    { code: "+34", iso2: "ES", name: "Spain", digits: { min: 9, max: 9 } },
    { code: "+94", iso2: "LK", name: "Sri Lanka", digits: { min: 9, max: 10 } },
    { code: "+249", iso2: "SD", name: "Sudan", digits: { min: 9, max: 9 } },
    { code: "+597", iso2: "SR", name: "Suriname", digits: { min: 7, max: 7 } },
    { code: "+268", iso2: "SZ", name: "Swaziland", digits: { min: 8, max: 8 } },
    { code: "+46", iso2: "SE", name: "Sweden", digits: { min: 7, max: 10 } },
    { code: "+41", iso2: "CH", name: "Switzerland", digits: { min: 9, max: 9 } },
    { code: "+963", iso2: "SY", name: "Syria", digits: { min: 9, max: 9 } },
    { code: "+886", iso2: "TW", name: "Taiwan", digits: { min: 9, max: 9 } },
    { code: "+992", iso2: "TJ", name: "Tajikistan", digits: { min: 9, max: 9 } },
    { code: "+255", iso2: "TZ", name: "Tanzania", digits: { min: 9, max: 9 } },
    { code: "+66", iso2: "TH", name: "Thailand", digits: { min: 9, max: 10 } },
    { code: "+228", iso2: "TG", name: "Togo", digits: { min: 8, max: 8 } },
    { code: "+690", iso2: "TK", name: "Tokelau", digits: { min: 5, max: 5 } },
    { code: "+676", iso2: "TO", name: "Tonga", digits: { min: 5, max: 8 } },
    { code: "+1868", iso2: "TT", name: "Trinidad and Tobago", digits: { min: 7, max: 7 } },
    { code: "+216", iso2: "TN", name: "Tunisia", digits: { min: 8, max: 8 } },
    { code: "+90", iso2: "TR", name: "Turkey", digits: { min: 10, max: 10 } },
    { code: "+993", iso2: "TM", name: "Turkmenistan", digits: { min: 8, max: 11 } },
    { code: "+1649", iso2: "TC", name: "Turks and Caicos Islands", digits: { min: 7, max: 7 } },
    { code: "+688", iso2: "TV", name: "Tuvalu", digits: { min: 5, max: 8 } },
    { code: "+971", iso2: "AE", name: "United Arab Emirates", digits: { min: 9, max: 9 } },
    { code: "+256", iso2: "UG", name: "Uganda", digits: { min: 9, max: 9 } },
    { code: "+44", iso2: "GB", name: "United Kingdom", digits: { min: 10, max: 10 } },
    { code: "+1", iso2: "US", name: "United States", digits: { min: 10, max: 10 } },
    { code: "+598", iso2: "UY", name: "Uruguay", digits: { min: 8, max: 8 } },
    { code: "+998", iso2: "UZ", name: "Uzbekistan", digits: { min: 9, max: 9 } },
    { code: "+678", iso2: "VU", name: "Vanuatu", digits: { min: 5, max: 7 } },
    { code: "+39", iso2: "VA", name: "Vatican City", digits: { min: 8, max: 8 } },
    { code: "+58", iso2: "VE", name: "Venezuela", digits: { min: 10, max: 10 } },
    { code: "+84", iso2: "VN", name: "Vietnam", digits: { min: 9, max: 10 } },
    { code: "+1340", iso2: "VI", name: "US Virgin Islands", digits: { min: 7, max: 7 } },
    { code: "+681", iso2: "WF", name: "Wallis and Futuna", digits: { min: 6, max: 6 } },
    { code: "+970", iso2: "PS", name: "West Bank", digits: { min: 9, max: 9 } },
    { code: "+967", iso2: "YE", name: "Yemen", digits: { min: 9, max: 9 } },
    { code: "+260", iso2: "ZM", name: "Zambia", digits: { min: 9, max: 9 } },
    { code: "+263", iso2: "ZW", name: "Zimbabwe", digits: { min: 9, max: 12 } },
];

export const VEHICLE_OPTIONS: VehicleCategory[] = [
  { category: "Land", vehicles: [
    { id: "bike", label: "Bike", icon: "🏍️", maxWeightKg: 25 },
    { id: "auto_rickshaw", label: "Auto Rickshaw", icon: "🛺", maxWeightKg: 500 },
    { id: "car", label: "Car", icon: "🚗", maxWeightKg: 400 },
    { id: "van", label: "Van", icon: "🚐", maxWeightKg: 1500 },
    { id: "truck", label: "Truck", icon: "🚛", maxWeightKg: 25000 },
    { id: "bus", label: "Bus", icon: "🚌", maxWeightKg: 2000 },
  ]},
  { category: "Water", vehicles: [
    { id: "speedboat", label: "Speedboat", icon: "🚤", maxWeightKg: 1000 },
    { id: "sailboat", label: "Sailboat", icon: "⛵", maxWeightKg: 2000 },
    { id: "cargo_ship", label: "Cargo Ship", icon: "🚢", maxWeightKg: 200000 },
    { id: "ferry", label: "Ferry", icon: "🛥️", maxWeightKg: 50000 },
  ]},
  { category: "Air", vehicles: [
    { id: "light_aircraft", label: "Light Aircraft", icon: "🛩️", maxWeightKg: 500 },
    { id: "cargo_plane", label: "Cargo Plane", icon: "✈️", maxWeightKg: 100000 },
    { id: "helicopter", label: "Helicopter", icon: "🚁", maxWeightKg: 1500 },
    { id: "drone", label: "Drone", icon: "🛸", maxWeightKg: 20 },
  ]},
];
